// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD60rEJIG09cxJSLngbRYIhXv33nOb1OSQ',
    appId: '1:688130460463:web:d7fd63e3c150b736a8afda',
    messagingSenderId: '688130460463',
    projectId: 'sih-hack-a3e98',
    authDomain: 'sih-hack-a3e98.firebaseapp.com',
    storageBucket: 'sih-hack-a3e98.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj9gs63fagBeKMk86U1dmTjaotvA2X27Q',
    appId: '1:688130460463:android:e64092cd5ccce008a8afda',
    messagingSenderId: '688130460463',
    projectId: 'sih-hack-a3e98',
    storageBucket: 'sih-hack-a3e98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUaXwnNlb_fHmFAe6_HK91LsjZzMwuMo0',
    appId: '1:688130460463:ios:a99d1a7e175897a8a8afda',
    messagingSenderId: '688130460463',
    projectId: 'sih-hack-a3e98',
    storageBucket: 'sih-hack-a3e98.appspot.com',
    iosBundleId: 'com.example.sihHack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUaXwnNlb_fHmFAe6_HK91LsjZzMwuMo0',
    appId: '1:688130460463:ios:3ef7ed7bf41c5021a8afda',
    messagingSenderId: '688130460463',
    projectId: 'sih-hack-a3e98',
    storageBucket: 'sih-hack-a3e98.appspot.com',
    iosBundleId: 'com.example.sihHack.RunnerTests',
  );
}
